//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDiaryRepository.Dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTACT()
        {
            this.CONTACT_AWARD = new HashSet<CONTACT_AWARD>();
            this.CONTACT_CATEGORY = new HashSet<CONTACT_CATEGORY>();
            this.CONTACT_CERTIFICATION = new HashSet<CONTACT_CERTIFICATION>();
            this.CONTACT_FOLDER = new HashSet<CONTACT_FOLDER>();
            this.CONTACT_MESSENGER = new HashSet<CONTACT_MESSENGER>();
            this.CONTACT_QUALIFICATION = new HashSet<CONTACT_QUALIFICATION>();
            this.CONTACT_RATES = new HashSet<CONTACT_RATES>();
            this.CONTACT_SKILLS = new HashSet<CONTACT_SKILLS>();
            this.CONTACT_WORK_HISTORY = new HashSet<CONTACT_WORK_HISTORY>();
        }
    
        public int CONTACT_ID { get; set; }
        public int USER_ID { get; set; }
        public int CONTACT_TYPE_ID { get; set; }
        public string BUSINESS_NAME { get; set; }
        public string BUSINESS_LOGO { get; set; }
        public string FULL_NAME { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public string MNAME { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public Nullable<int> STATE_ID { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public string ZIP_POSTAL { get; set; }
        public string PRIMARY_PHONE { get; set; }
        public string SECONDARY_PHONE { get; set; }
        public string OTHER_PHONE { get; set; }
        public string WEBSITE_URL { get; set; }
        public string FACEBOOK_ID { get; set; }
        public string TWITTER_ID { get; set; }
        public string GOOGLE_ID { get; set; }
        public string NOTES { get; set; }
        public string ABOUT_ME { get; set; }
        public Nullable<bool> IS_BUSINESS_NAME_PUBLIC { get; set; }
        public Nullable<bool> IS_PERSONAL_INFO_PUBLIC { get; set; }
        public Nullable<bool> IS_ADDRESS_PUBLIC { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
        public bool IS_ARCHIVED { get; set; }
        public Nullable<System.DateTime> ARCHIVED_ON { get; set; }
        public Nullable<int> ARCHIVED_BY { get; set; }
        public string LAST_ACTIVITY { get; set; }
        public Nullable<System.DateTime> LAST_ACTIVITY_ON { get; set; }
        public Nullable<bool> IS_PRIMARY { get; set; }
        public string TERMS_AND_CONDITIONS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_AWARD> CONTACT_AWARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_CATEGORY> CONTACT_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_CERTIFICATION> CONTACT_CERTIFICATION { get; set; }
        public virtual CONTACT_TYPE CONTACT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_FOLDER> CONTACT_FOLDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_MESSENGER> CONTACT_MESSENGER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_QUALIFICATION> CONTACT_QUALIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_RATES> CONTACT_RATES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_SKILLS> CONTACT_SKILLS { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_WORK_HISTORY> CONTACT_WORK_HISTORY { get; set; }
    }
}
