//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDiaryRepository.Dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT_WORK_HISTORY
    {
        public int WORK_HISTORY_ID { get; set; }
        public Nullable<int> CONTACT_ID { get; set; }
        public Nullable<int> CONTACT_CAT_ID { get; set; }
        public string POSITION_HELD { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string EMPLOYER_NAME { get; set; }
        public string ROLES_RESPONSIBILITIES { get; set; }
        public Nullable<bool> IS_ARCHIVED { get; set; }
    
        public virtual CONTACT CONTACT { get; set; }
    }
}
