//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDiaryRepository.Dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRY
    {
        public int COUNTRY_ID { get; set; }
        public string NAME { get; set; }
        public string FIPS104 { get; set; }
        public string ISO2 { get; set; }
        public string ISO3 { get; set; }
        public string ISON { get; set; }
        public string INTERNET { get; set; }
        public string CAPITAL { get; set; }
        public string MAP_REFERENCE { get; set; }
        public string NATIONALITY_SINGULAR { get; set; }
        public string NATIONALITY_PLURAL { get; set; }
        public string CURRENCY { get; set; }
        public string CURRENCY_CODE { get; set; }
        public Nullable<long> POPULATION { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> IS_ARCHIVED { get; set; }
    }
}
