//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDiaryRepository.Dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_HISTORY
    {
        public int HISTORY_ID { get; set; }
        public string SUBJECT { get; set; }
        public string BODY { get; set; }
        public string FROM_ADDR { get; set; }
        public string TO_ADDR { get; set; }
        public string CC_ADDR { get; set; }
        public string BCC_ADDR { get; set; }
        public System.DateTime SENT_ON { get; set; }
        public int EMAIL_TEMPLATE_ID { get; set; }
        public int USER_ID { get; set; }
    }
}
