//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDiaryRepository.Dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_TASK
    {
        public int TASK_ID { get; set; }
        public Nullable<int> JOB_ID { get; set; }
        public Nullable<int> JOB_AWARDED_ID { get; set; }
        public Nullable<int> TASK_TYPE_ID { get; set; }
        public Nullable<int> TASK_STATUS_ID { get; set; }
        public Nullable<int> TASK_PRIORITY_ID { get; set; }
        public string TASK { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> IS_COMPLETED { get; set; }
        public Nullable<System.DateTime> WORK_START_ON { get; set; }
        public Nullable<System.DateTime> WORK_END_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<int> ASSIGNED_TO { get; set; }
        public Nullable<int> ESTIMATED_HOURS { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
    }
}
