//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDiaryRepository.Dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_FOLDER
    {
        public int JOB_FOLDER_ID { get; set; }
        public Nullable<int> FOLDER_ID { get; set; }
        public Nullable<int> JOB_ID { get; set; }
        public Nullable<int> IS_ARCHIVED { get; set; }
    
        public virtual JOB JOB { get; set; }
    }
}
