//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDiaryRepository.Dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public int MENU_ID { get; set; }
        public string NAME { get; set; }
        public string DISPLAY_TEXT { get; set; }
        public double DISPLAY_ORDER { get; set; }
        public string NAVIGATE_URL { get; set; }
        public Nullable<int> PERMISSION_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string MENU_LOCATION { get; set; }
        public Nullable<bool> IS_ARCHIVED { get; set; }
    
        public virtual PERMISSION PERMISSION { get; set; }
    }
}
