//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDiaryRepository.Dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCREEN_CATEGORY
    {
        public int SCREEN_CAT_ID { get; set; }
        public string CAT_NAME { get; set; }
        public bool IS_PRODUCTIVE { get; set; }
    }
}
