//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDiaryRepository.Dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_STATUS
    {
        public int TASK_STATUS_ID { get; set; }
        public string NAME { get; set; }
        public string ICON_NAME { get; set; }
        public string CSS_STYLE_NAME { get; set; }
    }
}
