//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDiaryRepository.Dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.CONTACTs = new HashSet<CONTACT>();
        }
    
        public int USER_ID { get; set; }
        public int ROLE_ID { get; set; }
        public string FULL_NAME { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public string MNAME { get; set; }
        public string INITIALS { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public Nullable<int> STATE_ID { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public string ZIP_POSTAL { get; set; }
        public string IMAGE_URL { get; set; }
        public string PAYPAL_ACCOUNT_ID { get; set; }
        public string EMAIL { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string PRIMARY_PHONE { get; set; }
        public string SECONDARY_PHONE { get; set; }
        public string OTHER_PHONE { get; set; }
        public string SECURITY_QUESTION { get; set; }
        public string SECURITY_QUESTION_ANSWER { get; set; }
        public string NOTES { get; set; }
        public Nullable<System.DateTime> PWD_CHANGED_ON { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN_DATE { get; set; }
        public bool IS_LOCKED { get; set; }
        public Nullable<int> NUM_FAILED_LOGIN { get; set; }
        public Nullable<bool> IS_LOGGED_IN { get; set; }
        public Nullable<System.DateTime> ACTIVATED_ON { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
        public bool IS_ARCHIVED { get; set; }
        public Nullable<System.DateTime> ARCHIVED_ON { get; set; }
        public Nullable<int> ARCHIVED_BY { get; set; }
        public string MATTERMOST_USER_ID { get; set; }
        public string MATTERMOST_USER_PASSWORD { get; set; }
        public string MATTERMOST_ACCESS_TOKEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT> CONTACTs { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
