//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDiaryRepository.Dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_LOG
    {
        public int ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public string WINDOW_TITLE { get; set; }
        public Nullable<int> KEY_STROKES { get; set; }
        public Nullable<int> MOUSE_CLICKS { get; set; }
        public Nullable<int> SCROLLING { get; set; }
        public Nullable<int> TIME_SPENT_IN_SEC { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public Nullable<int> JOB_ID { get; set; }
    }
}
