//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleOfHangfire.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACH_FILE
    {
        public int ATTACH_FILE_ID { get; set; }
        public Nullable<int> FILE_RELATED_TYPE_ID { get; set; }
        public Nullable<int> MAIL_ID { get; set; }
        public Nullable<int> JOB_ID { get; set; }
        public Nullable<int> JOB_OFFER_ID { get; set; }
        public Nullable<int> ATTACHED_BY_USER_ID { get; set; }
        public string FILE_PATH { get; set; }
        public string FILE_NAME { get; set; }
    }
}
