//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleOfHangfire.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT_PORTFOLIO
    {
        public int PORTFOLIO_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> CONTACT_ID { get; set; }
        public string PROJECT_TITLE { get; set; }
        public Nullable<System.DateTime> COMPLETION_DATE { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<bool> IS_ARCHIVED { get; set; }
    }
}
