//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleOfHangfire.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTACT_CATEGORY()
        {
            this.CONTACT_AWARD = new HashSet<CONTACT_AWARD>();
            this.CONTACT_CERTIFICATION = new HashSet<CONTACT_CERTIFICATION>();
            this.CONTACT_FOLDER = new HashSet<CONTACT_FOLDER>();
            this.CONTACT_MESSENGER = new HashSet<CONTACT_MESSENGER>();
            this.CONTACT_QUALIFICATION = new HashSet<CONTACT_QUALIFICATION>();
            this.CONTACT_RATES = new HashSet<CONTACT_RATES>();
            this.CONTACT_SKILLS = new HashSet<CONTACT_SKILLS>();
        }
    
        public int CONTACT_CAT_ID { get; set; }
        public Nullable<int> CONTACT_ID { get; set; }
        public Nullable<int> CAT_ID { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
        public Nullable<bool> IS_ARCHIVED { get; set; }
        public Nullable<bool> IS_DEFAULT { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual CONTACT CONTACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_AWARD> CONTACT_AWARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_CERTIFICATION> CONTACT_CERTIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_FOLDER> CONTACT_FOLDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_MESSENGER> CONTACT_MESSENGER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_QUALIFICATION> CONTACT_QUALIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_RATES> CONTACT_RATES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_SKILLS> CONTACT_SKILLS { get; set; }
    }
}
