//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleOfHangfire.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENCY
    {
        public int CURRENCY_ID { get; set; }
        public string NAME { get; set; }
        public string SYMBOL { get; set; }
        public Nullable<bool> IS_ARCHIVED { get; set; }
        public Nullable<decimal> CURRENCY_DOLLOR_RATE { get; set; }
    }
}
