//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleOfHangfire.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDUCATION
    {
        public int EDUCATION_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> CONTACT_ID { get; set; }
        public Nullable<int> EDUCATION_TYPE_ID { get; set; }
        public string NAME { get; set; }
        public string YEAR { get; set; }
        public string ORGANIZATION { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
    }
}
