//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleOfHangfire.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOLDER_FILE
    {
        public int FILE_ID { get; set; }
        public Nullable<int> FOLDER_ID { get; set; }
        public Nullable<int> FILE_TYPE_ID { get; set; }
        public string NAME { get; set; }
        public string FILE_EXTENSION { get; set; }
        public Nullable<long> FILE_SIZE_IN_MB { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> ARCHIVED_ON { get; set; }
        public Nullable<int> ARCHIVED_BY { get; set; }
        public Nullable<bool> IS_ARCHIVED { get; set; }
    
        public virtual FILE_TYPE FILE_TYPE { get; set; }
        public virtual FOLDER FOLDER { get; set; }
    }
}
