//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleOfHangfire.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_OFFER_FOLDER
    {
        public int JOB_OFFER_FOLDER_ID { get; set; }
        public Nullable<int> JOB_OFFER_ID { get; set; }
        public Nullable<int> FOLDER_ID { get; set; }
        public string IS_ARCHIVED { get; set; }
    
        public virtual JOB_OFFER JOB_OFFER { get; set; }
    }
}
