//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleOfHangfire.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_TASKS_TIME_LOG
    {
        public int LOG_ID { get; set; }
        public Nullable<int> TASK_ID { get; set; }
        public Nullable<System.DateTime> START_ON { get; set; }
        public Nullable<System.DateTime> END_ON { get; set; }
    }
}
