//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleOfHangfire.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL
    {
        public int MAIL_ID { get; set; }
        public Nullable<int> MAIL_TYPE_ID { get; set; }
        public Nullable<System.DateTime> SENT_ON { get; set; }
        public Nullable<System.DateTime> REPLY_DATE { get; set; }
        public Nullable<int> MAIL_STATUS_ID { get; set; }
        public Nullable<int> SENT_BY_USER_ID { get; set; }
        public Nullable<int> TO_USER_ID { get; set; }
        public string SUBJECT { get; set; }
        public string BODY_TEXT { get; set; }
        public string BODY_HTML { get; set; }
        public Nullable<int> JOB_ID { get; set; }
        public Nullable<int> JOB_OFFER_ID { get; set; }
        public Nullable<bool> IS_ARCHIVED { get; set; }
        public Nullable<System.DateTime> ARCHIVED_ON { get; set; }
        public Nullable<int> ARCHIVED_BY { get; set; }
    
        public virtual MAIL_STATUS MAIL_STATUS { get; set; }
        public virtual MAIL_TYPE MAIL_TYPE { get; set; }
    }
}
