//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleOfHangfire.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_TRANSACTION
    {
        public int PAYMENT_ID { get; set; }
        public string PAYMENT_METHOD { get; set; }
        public string PAYPAL_RESPONSE_KEY { get; set; }
        public Nullable<int> BUYER_ID { get; set; }
        public Nullable<int> PROVIDER_ID { get; set; }
        public Nullable<int> JOB_AWARDED_ID { get; set; }
        public Nullable<decimal> PAID_AMOUNT { get; set; }
        public Nullable<decimal> CLIENT_AMOUNT { get; set; }
        public Nullable<decimal> SERVICE_FEE { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<bool> IS_CONFIRMED { get; set; }
        public Nullable<bool> IS_ARCHIVED { get; set; }
    }
}
