//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleOfHangfire.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKILL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SKILL()
        {
            this.CONTACT_SKILLS = new HashSet<CONTACT_SKILLS>();
        }
    
        public int SKILL_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int CLASS_ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
        public bool IS_ARCHIVED { get; set; }
        public Nullable<System.DateTime> ARCHIVED_ON { get; set; }
        public Nullable<int> ARCHIVED_BY { get; set; }
    
        public virtual CLASS CLASS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_SKILLS> CONTACT_SKILLS { get; set; }
    }
}
