//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleOfHangfire.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_MESSAGE
    {
        public int MSG_ID { get; set; }
        public string NAME { get; set; }
        public string DETAIL { get; set; }
        public string TYPE { get; set; }
        public string COMPONENT_NAME { get; set; }
        public int INSTITUTION_INSTITUTION_ID { get; set; }
    }
}
