//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exampleOfHangfire.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CONFIG_ENTRY
    {
        public int CONFIG_ID { get; set; }
        public string NAME { get; set; }
        public string DATA_TYPE { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public string CONFIG_VALUE { get; set; }
        public int DISPLAY_ORDER { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
    }
}
